<?php

namespace PackageVersions;

/**
 * This class is generated by ocramius/package-versions, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 */
final class Versions
{
    const VERSIONS = array (
  'bantu/ini-get-wrapper' => 'v1.0.1@4770c7feab370c62e23db4f31c112b7c6d90aee2',
  'deepdiver1975/tarstreamer' => 'v0.1.0@859a0170de120c66b042e6c0dbc1a9979c74669b',
  'doctrine/annotations' => 'v1.2.7@f25c8aab83e0c3e976fd7d19875f198ccf2f7535',
  'doctrine/cache' => 'v1.6.0@f8af318d14bdb0eff0336795b428b547bd39ccb6',
  'doctrine/collections' => 'v1.3.0@6c1e4eef75f310ea1b3e30945e9f06e652128b8a',
  'doctrine/common' => 'v2.6.1@a579557bc689580c19fee4e27487a67fe60defc0',
  'doctrine/dbal' => 'v2.5.9@0d2f8187d4b4c7b72d8e2acba359e25c36feaf5e',
  'doctrine/inflector' => 'v1.1.0@90b2128806bfde671b6952ab8bea493942c1fdae',
  'doctrine/lexer' => 'v1.0.1@83893c552fd2045dd78aef794c31e694c37c0b8c',
  'doctrine/migrations' => 'v1.5.0@c81147c0f2938a6566594455367e095150547f72',
  'guzzle/guzzle' => 'v3.8.1@4de0618a01b34aa1c8c33a3f13f396dcd3882eba',
  'guzzlehttp/guzzle' => '5.3.1@70f1fa53b71c4647bf2762c09068a95f77e12fb8',
  'guzzlehttp/ringphp' => '1.1.0@dbbb91d7f6c191e5e405e900e3102ac7f261bc0b',
  'guzzlehttp/streams' => '3.0.0@47aaa48e27dae43d39fc1cea0ccf0d84ac1a2ba5',
  'icewind/searchdav' => 'v0.3.1@3071937c64a5e45d23c2600e5524538694e03042',
  'icewind/streams' => '0.5.2@6bfd2fdbd99319f5e010d0a684409189a562cb1e',
  'interfasys/lognormalizer' => 'v1.0@d5e4c95e0b0ecc886b78aafda3773b3bcf2ec116',
  'jeremeamia/SuperClosure' => '2.1.0@b712f39c671e5ead60c7ebfe662545456aade833',
  'leafo/scssphp' => 'v0.6.7@562213cd803e42ea53b0735554794c4022d8db89',
  'league/flysystem' => '1.0.37@78b5cc4feb61a882302df4fbaf63b7662e5e4ccd',
  'lukasreschke/id3parser' => 'v0.0.1@cd3ba6e8918cc30883f01a3c24281cfe23b8877a',
  'mcnetic/zipstreamer' => 'v1.0@e57c198486242476587d04844084adbe8330581d',
  'mikemccabe/json-patch-php' => '0.1.0@b3af30a6aec7f6467c773cd49b2d974a70f7c0d4',
  'natxet/CssMin' => 'dev-master@003920e783c568c2d8fdf03999eebefb8479092a',
  'nikic/php-parser' => 'v1.4.1@f78af2c9c86107aa1a34cd1dbb5bbe9eeb0d9f51',
  'ocramius/package-versions' => '1.1.2@51e867c70f0799790b3e82276875414ce13daaca',
  'ocramius/proxy-manager' => '2.1.1@e18ac876b2e4819c76349de8f78ccc8ef1554cd7',
  'paragonie/random_compat' => 'v1.4.1@c7e26a21ba357863de030f0b9e701c7d04593774',
  'patchwork/jsqueeze' => 'v2.0.5@693d64850eab2ce6a7c8f7cf547e1ab46e69d542',
  'patchwork/utf8' => 'v1.2.6@f986d18f4e37ab70b792e977c7d85970cf84f164',
  'pear/archive_tar' => '1.4.1@fc2937c0e5a2a1c62a378d16394893172f970064',
  'pear/console_getopt' => 'v1.4.1@82f05cd1aa3edf34e19aa7c8ca312ce13a6a577f',
  'pear/pear-core-minimal' => 'v1.10.3@070f0b600b2caca2501e2c9b7e553016e4b0d115',
  'pear/pear_exception' => 'v1.0.0@8c18719fdae000b690e3912be401c76e406dd13b',
  'phpseclib/phpseclib' => '2.0.4@ab8028c93c03cc8d9c824efa75dc94f1db2369bf',
  'pimple/pimple' => 'v3.0.2@a30f7d6e57565a2e1a316e1baf2a483f788b258a',
  'psr/log' => '1.0.2@4ebe3a8bf773a19edfe0a84b6585ba3d401b724d',
  'punic/punic' => '1.6.5@7bc85ce1137cf52db4d2a6298256a4c4a24da99a',
  'rackspace/php-opencloud' => 'v1.16.0@d6b71feed7f9e7a4b52e0240a79f06473ba69c8c',
  'react/promise' => 'v2.2.1@3b6fca09c7d56321057fa8867c8dbe1abf648627',
  'sabre/dav' => '3.2.2@e987775e619728f12205606c9cc3ee565ffb1516',
  'sabre/event' => '3.0.0@831d586f5a442dceacdcf5e9c4c36a4db99a3534',
  'sabre/http' => '4.2.2@dd50e7260356f4599d40270826f9548b23efa204',
  'sabre/uri' => '1.2.1@ada354d83579565949d80b2e15593c2371225e61',
  'sabre/vobject' => '4.1.2@d0fde2fafa2a3dad1f559c2d1c2591d4fd75ae3c',
  'sabre/xml' => '1.5.0@59b20e5bbace9912607481634f97d05a776ffca7',
  'stecman/symfony-console-completion' => '0.7.0@5461d43e53092b3d3b9dbd9d999f2054730f4bbb',
  'swiftmailer/swiftmailer' => 'v5.4.5@cd142238a339459b10da3d8234220963f392540c',
  'symfony/console' => 'v3.1.3@f9e638e8149e9e41b570ff092f8007c477ef0ce5',
  'symfony/event-dispatcher' => 'v3.1.4@c0c00c80b3a69132c4e55c3e7db32b4a387615e5',
  'symfony/polyfill-mbstring' => 'v1.2.0@dff51f72b0706335131b00a7f49606168c582594',
  'symfony/polyfill-php70' => 'v1.1.1@386c1be9cad3ab531425211919e78c37971be4ce',
  'symfony/process' => 'v3.1.5@66de154ae86b1a07001da9fbffd620206e4faf94',
  'symfony/routing' => 'v3.1.4@8edf62498a1a4c57ba317664a4b698339c10cdf6',
  'symfony/yaml' => 'v3.2.8@acec26fcf7f3031e094e910b94b002fa53d4e4d6',
  'zendframework/zend-code' => '3.1.0@2899c17f83a7207f2d7f53ec2f421204d3beea27',
  'zendframework/zend-eventmanager' => '3.1.0@c3bce7b7d47c54040b9ae51bc55491c72513b75d',
  'nextcloud/3rdparty' => 'dev-doctrine-migrations@76e7a8e9848ac1c48230914d79a9c1548700cd8b',
);

    private function __construct()
    {
    }

    /**
     * @throws \OutOfBoundsException if a version cannot be located
     */
    public static function getVersion(string $packageName) : string
    {
        if (! isset(self::VERSIONS[$packageName])) {
            throw new \OutOfBoundsException(
                'Required package "' . $packageName . '" is not installed: cannot detect its version'
            );
        }

        return self::VERSIONS[$packageName];
    }
}
